import type {
    AssertCommandSpec,
    ClickCommandSpec,
    DragCommandSpec,
    ScrollCommandSpec,
    StepData,
    TypeCommandSpec,
    WaitUntilCommandSpec,
} from "@autonoma/engine";
import type { AgentExecutionOutput, ExecutionAgent, LeanExecutionResult } from "@autonoma/engine";
import type { MobileContext } from "../../platform";

/** The possible commands that the mobile agent can execute. */
export type MobileCommandSpec =
    | ClickCommandSpec
    | DragCommandSpec
    | TypeCommandSpec
    | AssertCommandSpec
    | ScrollCommandSpec
    | WaitUntilCommandSpec;

/** The steps generated by the mobile agent. */
export type AgentMobileStep = StepData<MobileCommandSpec>;
/** The output of a command execution by the mobile agent. */
export type MobileStepExecution = AgentExecutionOutput<MobileCommandSpec>;
/** The result of a test case execution by the mobile agent. */
export type MobileExecutionResult = LeanExecutionResult<MobileCommandSpec>;

/** The mobile execution agent. */
export type MobileAgent = ExecutionAgent<MobileCommandSpec, MobileContext>;
