services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgresql:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
