import type {
    AssertCommandSpec,
    ClickCommandSpec,
    DragCommandSpec,
    HoverCommandSpec,
    ReadCommandSpec,
    RefreshCommandSpec,
    SaveClipboardCommandSpec,
    ScrollCommandSpec,
    StepData,
    TypeCommandSpec,
    WaitUntilCommandSpec,
    WebClickOptions,
} from "@autonoma/engine";
import type { AgentExecutionOutput, ExecutionAgent, LeanExecutionResult } from "@autonoma/engine";
import type { WebContext } from "../../platform";

/** The possible commands that the Quara agent can execute. */
export type WebCommandSpec =
    | ClickCommandSpec<WebClickOptions>
    | DragCommandSpec
    | HoverCommandSpec
    | TypeCommandSpec
    | AssertCommandSpec
    | ScrollCommandSpec
    | RefreshCommandSpec
    | ReadCommandSpec
    | SaveClipboardCommandSpec
    | WaitUntilCommandSpec;

/** The steps generated by the Quara agent. */
export type AgentWebStep = StepData<WebCommandSpec>;
/** The output of a command execution by the Quara agent. */
export type WebStepExecution = AgentExecutionOutput<WebCommandSpec>;
/** The result of a test case execution by the Quara agent. */
export type WebExecutionResult = LeanExecutionResult<WebCommandSpec>;

/** The web execution agent. */
export type WebAgent = ExecutionAgent<WebCommandSpec, WebContext>;
