/**
 * Artifacts are files generated by the execution agent.
 *
 * The file structure is as follows:
 * - {{RUN_ARTIFACT_DIR}}
 *   - screenshots/
 *   - video.webm
 *   - steps.json
 *   - conversation.json
 *   - instruction.txt
 *
 * By default, this is stored under the current working directory in a directory called "artifacts".
 * This can be overridden by setting the ARTIFACT_DIR environment variable.
 */

import { existsSync, mkdirSync, renameSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { Screenshot } from "@autonoma/image";
import { type Logger, logger } from "@autonoma/logger";
import type { ModelMessage } from "ai";
import type { CommandSpec } from "../../commands";
import type { ExecutionResult } from "../agent";
import type { AgentExecutionOutput } from "../agent/tools/command-tool";
import { env } from "./env";

/**
 * Creates a timestamped run directory for artifacts.
 *
 * This is only used in local development mode.
 *
 * @param testName - The name of the test (will be sanitized for filesystem use)
 * @returns The absolute path to the created run directory
 */
function defaultRunDirectory(testName: string): string {
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    const safeName = testName.replace(/[^a-zA-Z0-9-_]/g, "_");
    return path.join(process.cwd(), "artifacts", `${timestamp}-${safeName}`);
}

export function getRunDirectory(testName: string): string {
    const runDir = env.ARTIFACT_DIR ?? defaultRunDirectory(testName);

    if (!existsSync(runDir)) mkdirSync(runDir, { recursive: true });

    return runDir;
}

export interface ArtifactWriterOptions {
    videoExtension: string;
}

type ArtifactSavingInputs<TSpec extends CommandSpec> = {
    executionResult: ExecutionResult<TSpec>;
    instruction: string;
    videoPath: string | null;
};

/**
 * Writes execution artifacts to a run directory.
 */
export class ArtifactWriter {
    private readonly logger: Logger;

    private readonly screenshotDir: string;

    constructor(
        private readonly runDir: string,
        private readonly options: ArtifactWriterOptions,
    ) {
        this.logger = logger.child({ name: this.constructor.name });
        this.screenshotDir = path.join(runDir, "screenshots");
        mkdirSync(this.screenshotDir, { recursive: true });
    }

    /**
     * Returns the run directory path.
     */
    getRunDir(): string {
        return this.runDir;
    }

    /**
     * Saves all execution artifacts: steps, screenshots, conversation, instruction, and optionally video.
     */
    saveAll<TSpec extends CommandSpec>({
        executionResult: { generatedSteps, conversation },
        instruction,
        videoPath,
    }: ArtifactSavingInputs<TSpec>): void {
        this.saveSteps(generatedSteps.map(({ executionOutput }) => executionOutput));

        for (const [
            index,
            {
                beforeMetadata: { screenshot: beforeScreenshot },
                afterMetadata: { screenshot: afterScreenshot },
            },
        ] of generatedSteps.entries())
            this.saveStepScreenshots(index, beforeScreenshot, afterScreenshot);

        this.saveConversation(conversation);

        this.saveInstruction(instruction);

        if (videoPath != null) this.saveVideo(videoPath);
    }

    /**
     * Saves screenshots for a single step.
     *
     * @param stepIndex - The 0-based index of the step
     * @param before - Screenshot taken before the command
     * @param after - Screenshot taken after the command
     */
    saveStepScreenshots(stepIndex: number, before: Screenshot, after: Screenshot): void {
        const beforePath = `screenshots/step-${stepIndex}-before.jpeg`;
        const afterPath = `screenshots/step-${stepIndex}-after.jpeg`;

        try {
            writeFileSync(path.join(this.runDir, beforePath), before.buffer);
        } catch (error) {
            this.logger.error("Failed to save before screenshot", error);
        }

        try {
            writeFileSync(path.join(this.runDir, afterPath), after.buffer);
        } catch (error) {
            this.logger.error("Failed to save after screenshot", error);
        }
    }

    /**
     * Saves the steps.json file.
     */
    saveSteps(steps: AgentExecutionOutput<CommandSpec>[]): void {
        try {
            writeFileSync(path.join(this.runDir, "steps.json"), JSON.stringify(steps, null, 2));
        } catch (error) {
            this.logger.error("Failed to save steps.json", error);
        }
    }

    /**
     * Saves the conversation.json file with sanitized messages.
     */
    saveConversation(messages: ModelMessage[]): void {
        try {
            writeFileSync(path.join(this.runDir, "conversation.json"), JSON.stringify(messages, null, 2));
        } catch (error) {
            this.logger.error("Failed to save conversation.json", error);
        }
    }

    /**
     * Saves the instruction.txt file.
     */
    saveInstruction(instruction: string): void {
        try {
            writeFileSync(path.join(this.runDir, "instruction.txt"), instruction ?? "");
        } catch (error) {
            this.logger.error("Failed to save instruction.txt", error);
        }
    }

    /**
     * Moves the video file to the standard location.
     *
     * @param videoPath - The path to the video file created by the platform driver
     */
    saveVideo(videoPath: string): void {
        try {
            renameSync(videoPath, path.join(this.runDir, `video.${this.options.videoExtension}`));
        } catch (error) {
            this.logger.error(`Failed to save video.${this.options.videoExtension}`, error);
        }
    }
}
